### ISSUE TITLE
Getting issues with SSL Certificate

### ISSUE THREAD

**Issue by manojjenago** [Athe-kunal/FinRL-project#1]
Hi Kunal,

Thanks for a beutiful and useful code to connect to Alpaca and get real time data.
However I am getting error for SSL. Seems the loop is not working for me. Please guide ...
`y", line 622, in __await_impl__
    transport, protocol = await self._create_connection()
  File "C:\Users\m\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1081, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\m\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1111, in _create_connection_transport
    await waiter
  File "C:\Users\m\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 528, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\m\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\m\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)
INFO:alpaca_trade_api.stream:starting stock data websocket connection
ERROR:alpaca_trade_api.stream:error during websocket communication: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)`

**Comment by Athe-kunal** [comment]
Hi @manojjenago 
Please first pass your API keys in the final_stream.py file. Log into Alpaca and get your API keys and then pass it in the file. It will work. Pass in your API keys [here](https://github.com/Athe-kunal/FinRL-project/issues/1). Follow this [video](https://youtu.be/OjiL6JMX-U8) to create an account. My credentials have expired.

**Comment by manojjenago** [comment]
> Hi @manojjenago Please first pass your API keys in the final_stream.py file. Log into Alpaca and get your API keys and then pass it in the file. It will work. Pass in your API keys [here](https://github.com/Athe-kunal/FinRL-project/issues/1). Follow this [video](https://youtu.be/OjiL6JMX-U8) to create an account. My credentials have expired.

Thanks for your quick reply, However I am using my own credentials for Alpaca to log in. Also I have checked the same API key and , secret key works for another program to fetch data.

I guess some others are getting it too from Alpaca..I can not get it resolved though with the solutions provided... Please let me know if you have any updates...for this..

https://forum.alpaca.markets/t/websocket-stopped-receiving-data-all-of-a-sudden/7004/3

Thanks ,
MJ

**Comment by manojjenago** [comment]
Hi Can you please copy a sample of bars.csv file in the mean time. 
Also I have noticed that there is no more .subscribe_crypto_bars in the stream class ( "stream.subscribe_crypto_bars(trade_bars, "ETHUSD")")... 

If you have any update code , please share ..
Thanks ,
MJ

**Comment by Athe-kunal** [comment]
Here you can see there is subscribe_crypto_bars, https://github.com/alpacahq/alpaca-trade-api-python/blob/master/alpaca_trade_api/stream.py#L744. Actually Stream is the v2, they have mentioned it

**Comment by manojjenago** [comment]
> Here you can see there is subscribe_crypto_bars, https://github.com/alpacahq/alpaca-trade-api-python/blob/master/alpaca_trade_api/stream.py#L744. Actually Stream is the v2, they have mentioned it

Thanks , I see it. I was looking on wrong location. However I am still getting the certificate error after trying a lot of solutions.
Not sure what was the change. It seems it get some SSL cerificates that has been expired and complains about it. However I have deleted the entry , but still gets error. Not sure why...
But thank you for such a beutiful peice of code and how we can use for multiple tickers visualization with Streamlit. It makes easier to visualize all tickers in one page.

Thanks again for your hard work and idea.
Thanks,
MJ

**Comment by Athe-kunal** [comment]
Glad to hear that, @manojjenago. Hoping to see you improve this repo and add some more functionality
